console.log("Ben")
console.log("Shinchan")
console.log("doremon")
console.log("chotabeam")
console.log("barbie")
console.log("nobita")
console.log("little krishna")
console.log("gloryia")
console.log("stuart little")
console.log("beam")